//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace support_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public int Report_Number_Issue { get; set; }
        public string Description { get; set; }
        public System.DateTime Note_Time { get; set; }
    
        public virtual Issue Issue { get; set; }
    }
}
